name: reinvent
channels:
  - rdkit
  - pytorch
  - OpenEye/label/dev
  - numba
  - conda-forge
  - defaults
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.2
  - cairo=1.14.12
  - certifi=2020.4.5.2
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - git=2.23.0
  - gitdb2=2.0.6
  - gitpython=2.1.13
  - glib=2.63.1
  - icc_rt=2018.0.2
  - icu=58.2
  - idna=2.9
  - imbalanced-learn=0.7.0
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.14.1
  - jpeg=9b
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.1.1
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - libblas=3.8.0
  - libboost=1.67.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libcxx=10.0.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.9
  - llvm-openmp=10.0.0
  - llvmlite=0.33.0rc1
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - more-itertools=8.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - ninja=1.9.0
  - notebook=6.0.3
  - numba=0.50.0rc1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openeye-toolkits=2017.10.1
  - openssl=1.1.1g
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - perl=5.26.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - pixman=0.38.0
  - pluggy=0.13.1
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - py=1.8.1
  - py-boost=1.67.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=5.4.2
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=0.4.0
  - pytz=2020.1
  - pyzmq=18.1.1
  - rdkit=2020.03.2.0
  - readline=7.0
  - requests=2.23.0
  - scikit-learn=0.23.1
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=46.2.0
  - six=1.14.0
  - smmap2=2.0.5
  - sqlite=3.31.1
  - tbb=2020.0
  - tbb4py=2020.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.8
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - bokeh==2.0.2
    - click==7.1.2
    - cloudpickle==1.4.1
    - contextvars==2.4
    - dill==0.3.1.1
    - distributed==2.16.0
    - fsspec==0.7.3
    - heapdict==1.0.1
    - immutables==0.14
    - locket==0.2.0
    - msgpack==1.0.0
    - pandarallel==1.4.8
    - partd==1.1.0
    - psutil==5.7.0
    - pyyaml==5.3.1
    - sortedcontainers==2.1.0
    - tblib==1.6.0
    - toolz==0.10.0
    - tqdm==4.46.0
    - typing-extensions==3.7.4.2
    - zict==2.0.0
